name: Generate parellele
on:
  workflow_dispatch: # déclenchement manuel
jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        server: [prod1, prod2, prod3, prod4, prod5, prod6, prod7, prod8]
    steps:
      - run: echo " j'imprime ${{ matrix.server}}"
