name: Generate parellele
on:
  workflow_dispatch: # déclenchement manuel
  push:              # et à chaque commit sur la branche principale
jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        server: [prod1, prod2, prod3, prod4, prod5, prod6, prod7, prod8]
    steps:
      - name: Deploy application
        uses: lgmorand/deploy-app@v1
          with:
            server: ${{ matrix.server}}
