name: Generate PDF optimized
on:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://doraj/github-action-pandoc:1.0
        with:
          args: "--standalone --output=readme.html readme.md"
      - uses: actions/upload-artifact@v1
        with:
          name: "Artifact"
          path: readme.html
